U
/****** Object:  Table [dbo].[B_BATCH_MAINTENANCE]    Script Date: 10/28/2014 11:18:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[B_BATCH_MAINTENANCE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BatchName] [nvarchar](200) NOT NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[NoOfRuns] [int] NULL,
	[Status] [nvarchar](50) NULL,
 CONSTRAINT [PK_B_BATCH_MAINTENANCE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


